### ISSUE TITLE
Button is not working

### ISSUE THREAD

**Issue by harshadkanziya-in** [xXDeathAbyssXx/wwebjs-sender#6]
I have use same example code. if I have send message with button then not working.
if I have remove button then send message

let embed = new WwebjsSender.MessageEmbed()
            .sizeEmbed(28)
            .setTitle("✅ | Successful process!")
            .setDescription("The process has been successful!")
            .addField("✔", "To confirm")
            .addField("❌", "To cancel")
            .addFields({
                name: "Now you have 2 buttons to choose!",
                value: "✔ or ❌",
            })
            .setFooter("WwebjsSender")
            .setTimestamp();

        let button1 = new WwebjsSender.MessageButton()
            .setCustomId("confirm")
            .setLabel("✔");

        let button2 = new WwebjsSender.MessageButton()
            .setCustomId("cancel")
            .setLabel("❌");

        WwebjsSender.send({
            client: client,
            number: from,
            embed: embed,
            button: [button1, button2],
        });

**Comment by xXDeathAbyssXx** [comment]
For now whatsapp-web.js can't send buttons yet, we need to wait...
